import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Vector3} from 'three';
import {BlockWorld,PickaxeBody,PickaxeSimulator,applyImpulse,config,sweepAABB} from './src/physics.js';
test('sweeps catch a block even when both endpoints are outside',()=>{const h=sweepAABB(new Vector3(0,20,0),new Vector3(0,-20,0),new Vector3(-1,-1,-1),new Vector3(1,1,1));assert.ok(h);assert.equal(h.t,.475);assert.equal(h.normal.y,1);});
test('off-center impulses create spin; center impulses do not',()=>{const a=new PickaxeBody(),b=new PickaxeBody();a.angularVelocity.set(0,0,0);b.angularVelocity.set(0,0,0);applyImpulse(a,new Vector3(),new Vector3(0,2,0));applyImpulse(b,new Vector3(1,0,0),new Vector3(0,2,0));assert.equal(a.angularVelocity.length(),0);assert.ok(b.angularVelocity.z>1);});
test('head impact breaks blocks without stopping the body',()=>{const w=new BlockWorld(),s=new PickaxeSimulator(w),b=new PickaxeBody(new Vector3(.5,6.8,0));b.angularVelocity.set(0,0,0);b.velocity.y=-65;s.add(b);for(let i=0;i<7;i++)s.step(config.fixedDt);assert.ok(s.stats.broken>=2,JSON.stringify(s.stats));assert.ok(b.velocity.y<0);assert.ok(b.position.y>0);});
test('handle damages far less and rebounds more strongly',()=>{function impact(head){const w=new BlockWorld(),s=new PickaxeSimulator(w),b=new PickaxeBody(new Vector3(.5,head?6:6.8,0));b.orientation.identity();if(head)b.orientation.setFromAxisAngle(new Vector3(0,0,1),Math.PI);b.angularVelocity.set(0,0,0);b.velocity.y=-10;s.add(b);for(let i=0;i<30;i++)s.step(config.fixedDt);return {s,b};}const head=impact(true),handle=impact(false);assert.ok(head.s.stats.broken>handle.s.stats.broken);assert.ok(handle.s.stats.handle>0);});
test('many independent bodies remain finite and settle',()=>{let seed=29;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const s=new PickaxeSimulator(new BlockWorld());for(let i=0;i<24;i++)s.add(new PickaxeBody(new Vector3((rand()-.5)*6,8+rand()*2,(rand()-.5)*.3),rand));for(let i=0;i<120*25;i++)s.step(config.fixedDt);for(const b of s.bodies){assert.ok(Number.isFinite(b.position.length()));assert.ok(b.position.y>-.1);assert.ok(b.velocity.length()<=config.maxVelocity+.001);assert.ok(Math.abs(b.orientation.length()-1)<1e-6);}const sleeping=s.bodies.filter(b=>b.sleeping).length;console.log(`settled: ${sleeping}/24, destroyed: ${s.stats.broken}`);assert.ok(sleeping>=20);});
