import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {PickaxeBody,PickaxeSimulator,BlockWorld,config} from './physics.js';
const scene=new T.Scene();scene.background=new T.Color('#18222e');scene.fog=new T.Fog('#18222e',24,65);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true});}catch(e){document.querySelector('#error').hidden=false;document.querySelector('#error').textContent='This experiment requires WebGL 2. Please open it in a browser with hardware acceleration enabled.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;document.body.prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(43,1,.1,100);camera.position.set(12,10.5,16);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,3.6,0);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.48;controls.minDistance=10;controls.maxDistance=32;
scene.add(new T.HemisphereLight('#d8eaff','#64717b',2));const sun=new T.DirectionalLight('#fff0d6',4);sun.position.set(-6,14,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14,near:.5,far:40});sun.shadow.bias=-.0002;scene.add(sun);const rim=new T.DirectionalLight('#8ebdff',2);rim.position.set(4,7,-7);scene.add(rim);
const ground=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:'#263541',roughness:.95}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const grid=new T.GridHelper(40,40,'#43525c','#34434e');grid.position.y=.006;grid.material.transparent=true;grid.material.opacity=.32;scene.add(grid);
const cubeGeometry=new T.BoxGeometry(.96,.96,.96),blocks=new Map(),fragments=[];
const world=new BlockWorld(block=>{const mesh=blocks.get(block);mesh.visible=false;for(let i=0;i<6;i++){const chip=new T.Mesh(chipGeometry,mesh.material);chip.position.copy(block.center).add(new T.Vector3((Math.random()-.5)*.7,(Math.random()-.5)*.7,(Math.random()-.5)*.7));scene.add(chip);fragments.push({mesh:chip,velocity:new T.Vector3((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),life:1.2});}});
for(const block of world.blocks){const shade=new T.Color().setHSL(.08+Math.random()*.025,.2,.43+Math.random()*.1);const mesh=new T.Mesh(cubeGeometry,new T.MeshStandardMaterial({color:shade,roughness:.88}));mesh.position.copy(block.center);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);blocks.set(block,mesh);const edges=new T.LineSegments(new T.EdgesGeometry(cubeGeometry),new T.LineBasicMaterial({color:'#302b26',transparent:true,opacity:.2}));mesh.add(edges);}
const chipGeometry=new T.BoxGeometry(.16,.16,.16),wood=new T.MeshStandardMaterial({color:'#9b592b',roughness:.8}),metal=new T.MeshStandardMaterial({color:'#c0d0dd',metalness:.78,roughness:.3}),grip=new T.MeshStandardMaterial({color:'#49392e',roughness:1});
const handleGeometry=new T.CylinderGeometry(.09,.075,1.86,10),collarGeometry=new T.CylinderGeometry(.14,.14,.25,10),gripGeometry=new T.CylinderGeometry(.092,.08,.43,10);
const outline=new T.Shape();outline.moveTo(-.99,.29);outline.lineTo(-.72,.59);outline.lineTo(-.28,.72);outline.lineTo(.28,.72);outline.lineTo(.72,.59);outline.lineTo(.99,.29);outline.lineTo(.54,.43);outline.lineTo(.16,.49);outline.lineTo(-.16,.49);outline.lineTo(-.54,.43);outline.closePath();const headGeometry=new T.ExtrudeGeometry(outline,{depth:.18,bevelEnabled:true,bevelThickness:.035,bevelSize:.035,bevelSegments:1,steps:1});headGeometry.translate(0,0,-.09);
function makePickaxe(){const group=new T.Group();for(const [geometry,material,y] of [[handleGeometry,wood,-.32],[headGeometry,metal,0],[collarGeometry,metal,.53],[gripGeometry,grip,-1.02]]){const mesh=new T.Mesh(geometry,material);mesh.position.y=y;mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}return group;}
const simulator=new PickaxeSimulator(world);
function drop(many=false){for(let i=0;i<(many?8:1);i++){const b=new PickaxeBody(new T.Vector3((Math.random()-.5)*(many?6:3),8+Math.random()*1.5,(Math.random()-.5)*.35));b.orientation.premultiply(new T.Quaternion().setFromEuler(new T.Euler((Math.random()-.5)*.7,Math.random()*.8,(Math.random()-.5)*1.8)));b.visual=makePickaxe();if(simulator.add(b)){scene.add(b.visual);b.syncVisual();}}}
document.querySelector('#drop').onclick=()=>drop();document.querySelector('#many').onclick=()=>drop(true);
let debug=false;const debugGroup=new T.Group();scene.add(debugGroup);const debugMaterial=new T.LineBasicMaterial({vertexColors:true,depthTest:false}),debugGeometry=new T.BufferGeometry(),debugLines=new T.LineSegments(debugGeometry,debugMaterial);debugLines.frustumCulled=false;debugLines.renderOrder=10;debugGroup.add(debugLines);
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='d'&&!e.repeat){debug=!debug;document.body.classList.toggle('debug',debug);debugGroup.visible=debug;}});debugGroup.visible=false;
function drawDebug(){const positions=[],colors=[];function line(a,b,color){positions.push(...a.toArray(),...b.toArray());const c=new T.Color(color);colors.push(...c.toArray(),...c.toArray());}function cross(p,size,color){for(const axis of [new T.Vector3(size,0,0),new T.Vector3(0,size,0),new T.Vector3(0,0,size)])line(p.clone().sub(axis),p.clone().add(axis),color);}
for(const b of simulator.bodies){cross(b.position,.13,'white');b.points().forEach((p,i)=>cross(p,.06,b.probes[i].kind==='head'?'#ffcf64':'#ff70cb'));b.sweeps.forEach(([a,z])=>line(a,z,'#4de0f5'));line(b.position,b.position.clone().addScaledVector(b.velocity,.18),'#79fa8a');line(b.position,b.position.clone().addScaledVector(b.angularVelocity,.18),'#c394ff');b.contacts.forEach(c=>line(c.point,c.point.clone().add(c.normal),'#ff665e'));}debugGeometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));debugGeometry.setAttribute('color',new T.Float32BufferAttribute(colors,3));document.querySelector('#debug').textContent=`D · DEBUG\nWhite: center of mass\nGold / pink: head / handle probes\nCyan: sweeps · green: velocity\nPurple: angular velocity · red: contact normal\n${simulator.bodies.length} bodies · ${simulator.bodies.filter(b=>b.sleeping).length} sleeping\n${simulator.stats.broken} broken · ${simulator.stats.head} head / ${simulator.stats.handle} handle impacts`;
}
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
let last=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.1);last=now;simulator.advance(dt);for(let i=fragments.length-1;i>=0;i--){const f=fragments[i];f.life-=dt;f.velocity.y-=config.gravity*dt;f.mesh.position.addScaledVector(f.velocity,dt);f.mesh.rotation.x+=dt*3;f.mesh.scale.setScalar(Math.max(0,f.life/1.2));if(f.life<=0){f.mesh.removeFromParent();fragments.splice(i,1);}}controls.update();if(debug)drawDebug();renderer.render(scene,camera);});
